import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import '@styles/globals.css';

const NotoSans = Noto_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={NotoSans.className}>
        <div className="inner">{children}</div>
      </body>
    </html>
  );
}
